### ISSUE TITLE
Is it possible to create multiple dataStore in same db using angular-localForage?

### ISSUE THREAD

**Issue by bobsilon** [ocombe/angular-localForage#51] opened 2014-12-18 21:58 UTC
Hi there. Is it possible to have multiple dataStore in IndexedDB using angular-localForage?
I tried this:
```javascript
var $tblStage = $localForage.createInstance({
    storeName   : 'tblStage', // name of the table
});
```
but it triggered an error which says:
>Error: A localForage instance with the name dbName is already defined.

I've read [this Question](http://stackoverflow.com/questions/20097662/how-to-create-multiple-object-stores-in-indexeddb) before but, is the only way is working with Raw IndexedDB? Or I missed something in my code? Any Idea?

**Comment by ocombe** [comment] 2015-01-06 14:49
Wow is it tomorrow already ? :P
Sorry I forgot to follow up on this :(

The problem is that when you create a new instance it uses the parameter "name" to keep track of the instances, and the name is also the name of the db. So if you define a new instance, you need to define a different name and it will create a new database...
I really did not think to this use case when I implemented the instances. I need to change the way I store instances to make this work...

Thanks for the report, I'll let you know when it's fixed.

**Comment by nathanbrock** [comment] 2015-01-15 12:56
Hi Olivier. Firstly, thanks for the great lib!

I've also come across the use case highlighted by @bobsilon, the desire to use two separate dataStores, in particular with IndexedDB/WebSQL. In my own case, I'm putting together some simple diary functionality with the need to store entry meta data in one table, and the body content in another.

For the moment I've made a couple of minor changes to the createInstance method as shown below, allowing the config property 'instanceName' to be used when provided, or to fall back to the 'name’ property as the key for the instances array.

*src/angular-localForage.js*
```javascript
LocalForageInstance.prototype.createInstance = function createInstance(config) {
    var instanceName = angular.isDefined(config.instanceName) ? config.instanceName : config.name;

    if (angular.isObject(config)) { // create new instance
        config = angular.extend({}, defaultConfig, config);
        if (angular.isDefined(lfInstances[instanceName])) {
            throw new Error('A localForage instance with the name ' + instanceName + ' is already defined.');
        }

        lfInstances[instanceName] = new LocalForageInstance(config);
        return lfInstances[instanceName];
    } else {
        throw new Error('The parameter should be a config object.')
    }
};
```
Simple enough, but currently only works when using the WebSQL driver. If you use IndexedDB the new instance will be created but the data won’t save as the following error is thrown.

```
"Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found."
```

When creating the second instance, I think because the same database name is being used the [onupgradeneeded function in the IndexSQL driver isn’t fired and the second object store isn’t created](https://github.com/mozilla/localForage/blob/master/src/drivers/indexeddb.js#L41). I’ve yet to get it working with IndexDB with the original suggestion made by @bobsilon, regarding incrementing the database version.

Additionally, with localstorage the key doesn't seem to namespace the dataStore eg 'name\key' instead of 'name\dataStore\key', but I could just be missing something!

It would be great if we could get this working. WebSQL works well for my current project platforms (Cordova for iOS / Android) but it would be great to get it working for IndexDB and LocalStorage.

Cheers!

**Comment by ocombe** [comment] 2015-01-15 14:35
Thanks for your investigation.
I'll probably have to do a breaking change to fix this problem. I'm not sure that instances are really used by a lot of people right now, so this shouldn't be too serious.
I'll let you know when I have the time to work on this (I don't have a lot of free time this month).

**Comment by saniyusuf** [comment] 2015-02-15 22:29
ANy news on this ?

**Comment by ocombe** [comment] 2015-02-16 13:17
I haven't had the time to work on it sorry, I had a busy beginning of 2015 :)
It's still on my todo list though.

**Comment by psalaets** [comment] 2015-05-13 15:24
@nathanbrock 

Your error could be related to mozilla/localForage#342

Relevant discussion also in mozilla/localForage#367

**Comment by saniyusuf** [comment] 2015-09-07 16:28
Any News?

**Comment by shardulP** [comment] 2015-10-05 09:17
Any updates on this ?

**Comment by ocombe** [comment] 2015-10-05 09:18
No sorry I kinda let this project down :(
If you know anyone interested in taking over that would be cool because I don't have much time these days.

**Comment by shardulP** [comment] 2015-10-05 09:24
This is good library

**Comment by shardulP** [comment] 2015-10-05 12:02
what if we passed storeName as an for config. I done come changes in file. Isn't it a better way to do it or not?

**Comment by ansorg** [comment] 2015-12-11 21:31
Since https://github.com/mozilla/localForage/issues/342 seems now fixed and actually allows multiple stores/tables per database/instance - could this be adapted here as well?

I wonder whether the approach by @nathanbrock above would just work now? Ok, going to try that ..

**Closed** 2016-03-26 13:00 UTC
Labels: bug

**Comment by hozkok** [comment] 2016-07-01 13:55
hi, fixed the issue there.

created a pull request

https://github.com/ocombe/angular-localForage/pull/119
