### ISSUE TITLE
Not able to find angular-localForage.js 

### ISSUE THREAD

**Issue by deeppatidar** [ocombe/angular-localForage#102] opened 2016-03-21 12:58 UTC
Not able to seen this angular-localForage.js  file localforage folder of bower_componenent and also getting the Failed to instantiate module LocalForageModule due to:  Module 'LocalForageModule' is not available! event added the dependencies in app.js .

var app = angular
  .module('demoAngularApp', [
    'cgBusy',
    'ngAnimate',
    'ngCookies',
    'ngResource',
    'ngRoute',
    'ngSanitize',
     'ngMask', 
     'ngCookies',
  'zingchart-angularjs',
  'LocalForageModule',   
  ]);

tried with both CDN and local file also
<script src="https://cdnjs.cloudflare.com/ajax/libs/localforage/1.4.0/localforage.js"></script>

**Comment by scotttrinh** [comment] 2016-06-15 16:56
You're installing with Bower, and it is being loaded after angular but before your app code in the HTML file, right? Can you give us some more context to your issue?

**Comment by scotttrinh** [comment] 2016-06-25 23:49
@deeppatidar 
Just checking to see if you ever got this working. I'm going to close the issue, but feel free to re-open if you need more help.

**Closed by scotttrinh** 2016-06-25 23:49 UTC
Labels: question

**Comment by deeppatidar** [comment] 2016-06-27 07:12
@scotttrinh  Thanks,
You its working, you can close it.

**Comment by binarytide** [comment] 2016-07-08 17:55
what was your solution?

**Comment by jessemarple** [comment] 2016-07-08 18:26
I'm having this same issue. Can @deeppatidar share what the solution was - even if it seems unrelated it could very much help.

**Comment by scotttrinh** [comment] 2016-07-08 20:15
Hey guys, what exactly is the issue you're seeing? Can you give me a plunker or even just the steps you use to reproduce the issue? I'm assuming it's something unrelated since if this was really an error, it just flat out wouldn't work for anyone, right?

Some things to check: I've you're concatenating this into your JS, make sure it's concatenated after angular, but before your own application scripts. If you're not, make sure it's referencing the correct location.

**Comment by deeppatidar** [comment] 2016-07-10 17:59
May be weird but when I  injecting "LocalForageModule" dependency  at first place in app.js, its working for me
